CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE TABLE public.lifeos_calendar_drafts ("user_id" text NOT NULL,"payload" jsonb NOT NULL,"expires_at" timestamp with time zone NOT NULL DEFAULT (now() + '1 day'::interval));
CREATE TABLE public.lifeos_calendar_events ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,"user_id" text NOT NULL,"calendar_id" text NOT NULL,"event_id" text NOT NULL,"title" text NOT NULL,"last_modified_by" text);
CREATE TABLE public.lifeos_change_log ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,"entity" text NOT NULL,"record_id" bigint NOT NULL,"creator" text NOT NULL,"actor" text NOT NULL,"operation" text NOT NULL,"changed_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.lifeos_config ("key" text NOT NULL,"value" text NOT NULL);
CREATE TABLE public.lifeos_events ("event_id" text NOT NULL,"user_id" text NOT NULL,"result" jsonb NOT NULL,"created_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.lifeos_invites ("id" uuid NOT NULL DEFAULT gen_random_uuid(),"code_hash" text NOT NULL,"label" text NOT NULL,"expires_at" timestamp with time zone NOT NULL,"claimed_by" text,"claimed_at" timestamp with time zone,"shared_owner" text);
CREATE TABLE public.lifeos_notifications ("id" uuid NOT NULL DEFAULT gen_random_uuid(),"user_id" text NOT NULL,"notification_key" text NOT NULL,"state" text NOT NULL,"retry_key" uuid NOT NULL DEFAULT gen_random_uuid(),"claimed_at" timestamp with time zone NOT NULL DEFAULT now(),"sent_at" timestamp with time zone);
CREATE TABLE public.lifeos_pending_postpone ("user_id" text NOT NULL,"task_id" bigint NOT NULL,"expires_at" timestamp with time zone NOT NULL DEFAULT (now() + '1 day'::interval));
CREATE TABLE public.lifeos_tasks ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,"user_id" text NOT NULL,"title" text NOT NULL,"category" text NOT NULL DEFAULT '生活'::text,"status" text NOT NULL DEFAULT '未開始'::text,"priority" text NOT NULL DEFAULT '一般'::text,"due_at" timestamp with time zone,"remind_at" timestamp with time zone,"original_text" text NOT NULL,"created_at" timestamp with time zone NOT NULL DEFAULT now(),"updated_at" timestamp with time zone NOT NULL DEFAULT now(),"completed_at" timestamp with time zone,"last_modified_by" text);
CREATE TABLE public.lifeos_test_reminders ("user_id" text NOT NULL,"scheduled_at" timestamp with time zone NOT NULL DEFAULT now(),"due_at" timestamp with time zone NOT NULL,"state" text NOT NULL DEFAULT 'pending'::text,"retry_key" uuid NOT NULL DEFAULT gen_random_uuid(),"claimed_at" timestamp with time zone,"sent_at" timestamp with time zone);
CREATE TABLE public.lifeos_users ("user_id" text NOT NULL,"label" text NOT NULL,"assistant_mode" boolean NOT NULL DEFAULT false,"notifications" boolean NOT NULL DEFAULT false,"draft" jsonb,"updated_at" timestamp with time zone NOT NULL DEFAULT now(),"shared_owner" text,"share_tasks" boolean NOT NULL DEFAULT false,"share_calendar" boolean NOT NULL DEFAULT false);
ALTER TABLE public.lifeos_config ADD CONSTRAINT lifeos_config_pkey PRIMARY KEY (key);
ALTER TABLE public.lifeos_invites ADD CONSTRAINT lifeos_invites_pkey PRIMARY KEY (id);
ALTER TABLE public.lifeos_invites ADD CONSTRAINT lifeos_invites_code_hash_key UNIQUE (code_hash);
ALTER TABLE public.lifeos_users ADD CONSTRAINT lifeos_users_pkey PRIMARY KEY (user_id);
ALTER TABLE public.lifeos_tasks ADD CONSTRAINT lifeos_tasks_title_check CHECK (((length(title) >= 1) AND (length(title) <= 500)));
ALTER TABLE public.lifeos_tasks ADD CONSTRAINT lifeos_tasks_status_check CHECK ((status = ANY (ARRAY['未開始'::text, '進行中'::text, '等待對方'::text, '完成'::text, '取消'::text])));
ALTER TABLE public.lifeos_tasks ADD CONSTRAINT lifeos_tasks_priority_check CHECK ((priority = ANY (ARRAY['一般'::text, '重要'::text])));
ALTER TABLE public.lifeos_tasks ADD CONSTRAINT lifeos_tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.lifeos_events ADD CONSTRAINT lifeos_events_pkey PRIMARY KEY (event_id);
ALTER TABLE public.lifeos_notifications ADD CONSTRAINT lifeos_notifications_state_check CHECK ((state = ANY (ARRAY['claimed'::text, 'sent'::text, 'failed'::text])));
ALTER TABLE public.lifeos_notifications ADD CONSTRAINT lifeos_notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.lifeos_notifications ADD CONSTRAINT lifeos_notifications_user_id_notification_key_key UNIQUE (user_id, notification_key);
ALTER TABLE public.lifeos_test_reminders ADD CONSTRAINT lifeos_test_reminders_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'claimed'::text, 'sent'::text, 'failed'::text])));
ALTER TABLE public.lifeos_test_reminders ADD CONSTRAINT lifeos_test_reminders_pkey PRIMARY KEY (user_id);
ALTER TABLE public.lifeos_calendar_drafts ADD CONSTRAINT lifeos_calendar_drafts_pkey PRIMARY KEY (user_id);
ALTER TABLE public.lifeos_calendar_events ADD CONSTRAINT lifeos_calendar_events_pkey PRIMARY KEY (id);
ALTER TABLE public.lifeos_calendar_events ADD CONSTRAINT lifeos_calendar_events_user_id_calendar_id_event_id_key UNIQUE (user_id, calendar_id, event_id);
ALTER TABLE public.lifeos_pending_postpone ADD CONSTRAINT lifeos_pending_postpone_pkey PRIMARY KEY (user_id);
ALTER TABLE public.lifeos_change_log ADD CONSTRAINT lifeos_change_log_pkey PRIMARY KEY (id);
ALTER TABLE public.lifeos_tasks ADD CONSTRAINT lifeos_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES lifeos_users(user_id);
ALTER TABLE public.lifeos_notifications ADD CONSTRAINT lifeos_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES lifeos_users(user_id);
ALTER TABLE public.lifeos_test_reminders ADD CONSTRAINT lifeos_test_reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES lifeos_users(user_id);
ALTER TABLE public.lifeos_calendar_drafts ADD CONSTRAINT lifeos_calendar_drafts_user_id_fkey FOREIGN KEY (user_id) REFERENCES lifeos_users(user_id);
ALTER TABLE public.lifeos_calendar_events ADD CONSTRAINT lifeos_calendar_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES lifeos_users(user_id);
ALTER TABLE public.lifeos_pending_postpone ADD CONSTRAINT lifeos_pending_postpone_user_id_fkey FOREIGN KEY (user_id) REFERENCES lifeos_users(user_id);
ALTER TABLE public.lifeos_pending_postpone ADD CONSTRAINT lifeos_pending_postpone_task_id_fkey FOREIGN KEY (task_id) REFERENCES lifeos_tasks(id);
CREATE OR REPLACE FUNCTION public.lifeos_calendar_dispatch(p jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare uid text:=p->>'user_id'; a text:=p->>'action'; r jsonb;
begin
 if uid is null or uid !~ '^U[0-9a-f]{32}$' or not exists(select 1 from public.lifeos_users where user_id=uid) then
  return jsonb_build_object('error','not_enrolled');
 end if;
 perform set_config('lifeos.actor',uid,true);
 perform pg_advisory_xact_lock(hashtextextended(coalesce((select shared_owner from public.lifeos_users where user_id=uid),uid),0));
 if a='calendar_draft' then
  insert into public.lifeos_calendar_drafts(user_id,payload) values(uid,p->'payload')
   on conflict(user_id) do update set payload=excluded.payload,expires_at=now()+interval '1 day';
  return jsonb_build_object('ok',true);
 elsif a='calendar_get_draft' then
  select payload into r from public.lifeos_calendar_drafts where user_id=uid and expires_at>now();
  if r->>'operation' in ('update','cancel') and not exists(select 1 from public.lifeos_calendar_events e where e.calendar_id=r->>'calendar_id' and e.event_id=r->>'event_id' and public.lifeos_can_access(uid,e.user_id,'calendar')) then
   delete from public.lifeos_calendar_drafts where user_id=uid;
   r:=null;
  end if;
  return jsonb_build_object('draft',r);
 elsif a='calendar_discard' then
  delete from public.lifeos_calendar_drafts where user_id=uid;
  return jsonb_build_object('ok',true);
 elsif a='calendar_save' then
  if exists(select 1 from public.lifeos_calendar_events where calendar_id=p->>'calendar_id' and event_id=p->>'event_id' and not public.lifeos_can_access(uid,user_id,'calendar')) then return jsonb_build_object('error','not_authorized'); end if;
  update public.lifeos_calendar_events set title=p->>'title' where calendar_id=p->>'calendar_id' and event_id=p->>'event_id' and public.lifeos_can_access(uid,user_id,'calendar') returning to_jsonb(lifeos_calendar_events.*) into r;
  if not found then
  insert into public.lifeos_calendar_events(user_id,calendar_id,event_id,title)
    values(uid,p->>'calendar_id',p->>'event_id',p->>'title')
    on conflict(user_id,calendar_id,event_id) do update set title=excluded.title returning to_jsonb(lifeos_calendar_events.*) into r;
  end if;
  delete from public.lifeos_calendar_drafts where user_id=uid and payload->>'event_id'=p->>'event_id';
  return jsonb_build_object('event',r);
 elsif a='calendar_events' then
  select coalesce(jsonb_agg(to_jsonb(e)),'[]'::jsonb) into r from public.lifeos_calendar_events e where public.lifeos_can_access(uid,user_id,'calendar');
  return jsonb_build_object('events',r);
 elsif a='calendar_event' then
  select to_jsonb(e) into r from public.lifeos_calendar_events e where public.lifeos_can_access(uid,user_id,'calendar') and id=(p->>'id')::bigint;
  return jsonb_build_object('event',r);
 end if;
 return jsonb_build_object('error','invalid_action');
end $function$

CREATE OR REPLACE FUNCTION public.lifeos_can_access(actor text, creator text, kind text)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public', 'pg_temp'
AS $function$
select exists(select 1 from lifeos_users a join lifeos_users c on c.user_id=creator join lifeos_users owner on owner.user_id=coalesce(a.shared_owner,a.user_id)
where a.user_id=actor and (actor=creator or (coalesce(a.shared_owner,a.user_id)=coalesce(c.shared_owner,c.user_id) and case kind when 'task' then owner.share_tasks when 'calendar' then owner.share_calendar else false end)));
$function$

CREATE OR REPLACE FUNCTION public.lifeos_confirm_tasks(p jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
 uid text:=p->>'user_id'; eid text:=p->>'event_id';
 d jsonb; res jsonb; item jsonb; rows jsonb:='[]'::jsonb;
 old_ids bigint[]; task public.lifeos_tasks%rowtype;
begin
 if p->>'action' is distinct from 'confirm_tasks' or uid is null or uid !~ '^U[0-9a-f]{32}$' then
   return jsonb_build_object('error','invalid_action');
 end if;
 perform set_config('lifeos.actor',uid,true);
 perform pg_advisory_xact_lock(hashtextextended(coalesce((select shared_owner from public.lifeos_users where user_id=uid),uid),0));
 if eid is not null then
   select result into res from public.lifeos_events where user_id=uid and event_id=eid;
   if found then return res; end if;
 end if;
 select draft into d from public.lifeos_users where user_id=uid;
 select coalesce(array_agg(id),'{}'::bigint[]) into old_ids from public.lifeos_tasks where public.lifeos_can_access(uid,user_id,'task');
 res:=public.lifeos_dispatch(p||jsonb_build_object('action','confirm'));
 if res ? 'error' then return res; end if;
 for item in select value from jsonb_array_elements(res->'tasks') loop
   select * into task from public.lifeos_tasks where public.lifeos_can_access(uid,user_id,'task') and id=(item->>'id')::bigint;
   if not found then raise exception 'Owned task missing'; end if;
   -- Only initialize new tasks. Never overwrite status of a merged existing task.
   if not(task.id=any(old_ids)) and task.status='未開始' and exists(
     select 1 from jsonb_array_elements(d->'tasks') x where x->>'title'=task.title
       and x->>'original_text'=task.original_text and x->>'status'='等待對方') then
     update public.lifeos_tasks set status='等待對方',updated_at=now() where id=task.id and public.lifeos_can_access(uid,user_id,'task') returning * into task;
   end if;
   rows:=rows||jsonb_build_array(to_jsonb(task));
 end loop;
 res:=jsonb_build_object('tasks',rows);
 if eid is not null then update public.lifeos_events set result=res where user_id=uid and event_id=eid; end if;
 return res;
end $function$

CREATE OR REPLACE FUNCTION public.lifeos_dispatch(p jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  a text := p->>'action';
  uid text := p->>'user_id';
  eid text := p->>'event_id';
  u public.lifeos_users%rowtype;
  inv public.lifeos_invites%rowtype;
  t jsonb;
  res jsonb;
  rows jsonb := '[]'::jsonb;
  nt public.lifeos_tasks%rowtype;
  n public.lifeos_notifications%rowtype;
begin
  if a = 'notification_users' then
    select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) into rows
      from (select user_id, label from public.lifeos_users where notifications) x;
    return jsonb_build_object('users',rows);
  end if;
  if uid is null or uid !~ '^U[0-9a-f]{32}$' then
    return jsonb_build_object('error','invalid_user');
  end if;
  -- Serialize operations per user and make webhook retries idempotent.
  perform set_config('lifeos.actor',uid,true);
 perform pg_advisory_xact_lock(hashtextextended(coalesce((select shared_owner from public.lifeos_users where user_id=uid),uid),0));
  if eid is not null then
    select result into res from public.lifeos_events where event_id=eid and user_id=uid;
    if found then return res; end if;
  end if;
  select * into u from public.lifeos_users where user_id=uid;
  if a = 'enroll' then
    if found then
      res := jsonb_build_object('user',to_jsonb(u),'already_enrolled',true);
    else
      select * into inv from public.lifeos_invites
        where code_hash=p->>'code_hash' and claimed_by is null and expires_at>now() for update;
      if not found then return jsonb_build_object('error','invalid_invite'); end if;
      update public.lifeos_invites set claimed_by=uid,claimed_at=now() where id=inv.id;
      insert into public.lifeos_users(user_id,label,assistant_mode,shared_owner) values(uid,inv.label,true,inv.shared_owner) returning * into u;
      res := jsonb_build_object('user',to_jsonb(u));
    end if;
  elsif not found then
    return jsonb_build_object('error','not_enrolled');
  elsif a = 'get_user' then
    return jsonb_build_object('user',to_jsonb(u)||jsonb_build_object('calendar_shared',coalesce((select share_calendar from public.lifeos_users where user_id=coalesce(u.shared_owner,uid)),false)));
  elsif a = 'mode' then
    update public.lifeos_users set assistant_mode=(p->>'enabled')::boolean, updated_at=now() where user_id=uid;
    res := jsonb_build_object('ok',true);
  elsif a = 'notifications' then
    update public.lifeos_users set notifications=(p->>'enabled')::boolean, updated_at=now() where user_id=uid;
    res := jsonb_build_object('ok',true);
  elsif a = 'draft' then
    if jsonb_typeof(p->'tasks') <> 'array' or jsonb_array_length(p->'tasks') not between 1 and 10 then
      return jsonb_build_object('error','invalid_draft');
    end if;
    update public.lifeos_users set draft=jsonb_build_object('tasks',p->'tasks','created_at',now()),updated_at=now() where user_id=uid;
    res := jsonb_build_object('ok',true);
  elsif a = 'discard' then
    update public.lifeos_users set draft=null,updated_at=now() where user_id=uid;
    res := jsonb_build_object('ok',true);
  elsif a = 'confirm' then
    if u.draft is null then return jsonb_build_object('error','no_draft'); end if;
    if (u.draft->>'created_at')::timestamptz < now()-interval '1 day' then
      update public.lifeos_users set draft=null where user_id=uid;
      return jsonb_build_object('error','expired_draft');
    end if;
    for t in select value from jsonb_array_elements(u.draft->'tasks') loop
      select * into nt from public.lifeos_tasks
        where public.lifeos_can_access(uid,user_id,'task') and status not in ('完成','取消') and title=t->>'title'
        and due_at is not distinct from nullif(t->>'due_at','')::timestamptz limit 1;
      if not found then
        insert into public.lifeos_tasks(user_id,title,category,priority,due_at,remind_at,original_text)
          values(uid,t->>'title',coalesce(t->>'category','生活'),coalesce(t->>'priority','一般'),
            nullif(t->>'due_at','')::timestamptz,nullif(t->>'remind_at','')::timestamptz,t->>'original_text') returning * into nt;
      end if;
      rows := rows || jsonb_build_array(to_jsonb(nt));
    end loop;
    update public.lifeos_users set draft=null,updated_at=now() where user_id=uid;
    res := jsonb_build_object('tasks',rows);
  elsif a = 'list' then
    select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) into rows from
      (select * from public.lifeos_tasks where public.lifeos_can_access(uid,user_id,'task') and
        (coalesce((p->>'include_closed')::boolean,false) or status not in ('完成','取消'))
        order by due_at nulls last, id limit 200) x;
    return jsonb_build_object('tasks',rows,'truncated',
      (select count(*)>200 from public.lifeos_tasks where public.lifeos_can_access(uid,user_id,'task') and
        (coalesce((p->>'include_closed')::boolean,false) or status not in ('完成','取消'))));
  elsif a = 'update' then
    if p ? 'status' and p->>'status' not in ('未開始','進行中','等待對方','完成','取消') then
      return jsonb_build_object('error','invalid_status');
    end if;
    update public.lifeos_tasks set
      status=coalesce(p->>'status',status),
      due_at=case when p ? 'due_at' then nullif(p->>'due_at','')::timestamptz else due_at end,
      -- A postponement invalidates the old reminder.
      remind_at=case when p ? 'due_at' then null else remind_at end,
      completed_at=case when p->>'status'='完成' then now()
        when p ? 'status' then null else completed_at end,
      updated_at=now()
      where public.lifeos_can_access(uid,user_id,'task') and id=(p->>'task_id')::bigint returning * into nt;
    if not found then return jsonb_build_object('error','not_found'); end if;
    res := jsonb_build_object('task',to_jsonb(nt));
  elsif a = 'notification_claim' then
    if not u.notifications then return jsonb_build_object('error','disabled'); end if;
    if (select count(*) from public.lifeos_notifications where user_id=uid
        and claimed_at >= date_trunc('month', now() at time zone 'Asia/Taipei') at time zone 'Asia/Taipei') >= 60 then
      return jsonb_build_object('error','monthly_cap');
    end if;
    insert into public.lifeos_notifications(user_id,notification_key,state)
      values(uid,p->>'key','claimed') on conflict do nothing returning * into n;
    if not found then
      select * into n from public.lifeos_notifications where user_id=uid and notification_key=p->>'key' for update;
      if n.state='sent' or (n.state='claimed' and n.claimed_at>now()-interval '10 minutes')
        or n.claimed_at<now()-interval '23 hours' then
        return jsonb_build_object('error','already_claimed');
      end if;
      update public.lifeos_notifications set state='claimed',claimed_at=now() where id=n.id;
    end if;
    return jsonb_build_object('notification',to_jsonb(n));
  elsif a = 'notification_finish' then
    update public.lifeos_notifications set state=case when (p->>'sent')::boolean then 'sent' else 'failed' end,
      sent_at=case when (p->>'sent')::boolean then now() else null end
      where user_id=uid and id=(p->>'notification_id')::uuid;
    res := jsonb_build_object('ok',true);
  else
    return jsonb_build_object('error','invalid_action');
  end if;
  if eid is not null then insert into public.lifeos_events(event_id,user_id,result) values(eid,uid,res) on conflict do nothing; end if;
  return res;
end;
$function$

CREATE OR REPLACE FUNCTION public.lifeos_postpone_dispatch(p jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare uid text:=p->>'user_id'; a text:=p->>'action'; nt public.lifeos_tasks%rowtype; pending public.lifeos_pending_postpone%rowtype; r jsonb;
begin
 if uid is null or uid !~ '^U[0-9a-f]{32}$' or not exists(select 1 from public.lifeos_users where user_id=uid) then return jsonb_build_object('error','not_enrolled'); end if;
 perform set_config('lifeos.actor',uid,true);
 perform pg_advisory_xact_lock(hashtextextended(coalesce((select shared_owner from public.lifeos_users where user_id=uid),uid),0));
 if a='postpone_get' then
  select jsonb_build_object('task_id',t.id,'title',t.title,'expires_at',x.expires_at) into r
   from public.lifeos_pending_postpone x join public.lifeos_tasks t on t.id=x.task_id and public.lifeos_can_access(x.user_id,t.user_id,'task')
   where x.user_id=uid and x.expires_at>now() and t.status not in ('完成','取消');
  return jsonb_build_object('pending',r);
 elsif a='postpone_start' then
  select * into nt from public.lifeos_tasks where public.lifeos_can_access(uid,user_id,'task') and id=(p->>'task_id')::bigint and status not in ('完成','取消');
  if not found then return jsonb_build_object('error','task_closed'); end if;
  insert into public.lifeos_pending_postpone(user_id,task_id) values(uid,nt.id)
   on conflict(user_id) do update set task_id=excluded.task_id,expires_at=now()+interval '1 day';
  return jsonb_build_object('ok',true);
 elsif a='postpone_cancel' then
  delete from public.lifeos_pending_postpone where user_id=uid;
  return jsonb_build_object('ok',true);
 elsif a='postpone_finish' then
  if p->>'event_id' is not null then
   select result into r from public.lifeos_events where event_id=p->>'event_id' and user_id=uid;
   if found then return r; end if;
  end if;
  select * into pending from public.lifeos_pending_postpone where user_id=uid and expires_at>now();
  if not found then return jsonb_build_object('error','no_pending'); end if;
  update public.lifeos_tasks set due_at=(p->>'due_at')::timestamptz,remind_at=null,updated_at=now()
   where public.lifeos_can_access(uid,user_id,'task') and id=pending.task_id and status not in ('完成','取消') returning * into nt;
  if not found then return jsonb_build_object('error','task_closed'); end if;
  delete from public.lifeos_pending_postpone where user_id=uid;
  r:=jsonb_build_object('task',to_jsonb(nt));
  if p->>'event_id' is not null then insert into public.lifeos_events(event_id,user_id,result) values(p->>'event_id',uid,r) on conflict do nothing; end if;
  return r;
 end if;
 return jsonb_build_object('error','invalid_action');
end $function$

CREATE OR REPLACE FUNCTION public.lifeos_record_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare actor text:=coalesce(nullif(current_setting('lifeos.actor',true),''),new.user_id);
begin
 if tg_op='UPDATE' and new.user_id is distinct from old.user_id then raise exception 'Creator cannot change'; end if;
 new.last_modified_by:=actor;
 insert into lifeos_change_log(entity,record_id,creator,actor,operation) values(tg_table_name,new.id,new.user_id,actor,tg_op);
 return new;
end $function$

CREATE OR REPLACE FUNCTION public.lifeos_test_dispatch(p jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare uid text:=p->>'user_id'; a text:=p->>'action'; r public.lifeos_test_reminders%rowtype; rows jsonb;
begin
  if a='test_users' then
    select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) into rows from
      (select user_id from public.lifeos_test_reminders where state<>'sent' and due_at<=now()
        and due_at>now()-interval '15 minutes' limit 20) x;
    return jsonb_build_object('users',rows);
  end if;
  if uid is null or uid !~ '^U[0-9a-f]{32}$' or not exists(select 1 from public.lifeos_users where user_id=uid) then
    return jsonb_build_object('error','not_enrolled');
  end if;
  perform pg_advisory_xact_lock(hashtextextended(uid,0));
  select * into r from public.lifeos_test_reminders where user_id=uid for update;
  if a='test_schedule' then
    if found and (r.scheduled_at at time zone 'Asia/Taipei')::date=(now() at time zone 'Asia/Taipei')::date then
      return jsonb_build_object('already_scheduled',true,'state',r.state,'due_at',r.due_at);
    end if;
    insert into public.lifeos_test_reminders(user_id,due_at) values(uid,now()+interval '1 minute')
      on conflict(user_id) do update set scheduled_at=now(),due_at=now()+interval '1 minute',state='pending',
        retry_key=gen_random_uuid(),claimed_at=null,sent_at=null returning * into r;
    return jsonb_build_object('state',r.state,'due_at',r.due_at);
  elsif not found then return jsonb_build_object('error','not_found');
  elsif a='test_claim' then
    if r.state='sent' or r.due_at>now() or r.due_at<now()-interval '15 minutes' or
      (r.state='claimed' and r.claimed_at>now()-interval '2 minutes') then
      return jsonb_build_object('error','not_due');
    end if;
    update public.lifeos_test_reminders set state='claimed',claimed_at=now() where user_id=uid returning * into r;
    return jsonb_build_object('notification',to_jsonb(r));
  elsif a='test_finish' then
    update public.lifeos_test_reminders set state=case when (p->>'sent')::boolean then 'sent' else 'failed' end,
      sent_at=case when (p->>'sent')::boolean then now() else null end
      where user_id=uid and retry_key=(p->>'retry_key')::uuid;
    return jsonb_build_object('ok',true);
  end if;
  return jsonb_build_object('error','invalid_action');
end $function$

CREATE TRIGGER lifeos_task_history BEFORE INSERT OR UPDATE ON public.lifeos_tasks FOR EACH ROW EXECUTE FUNCTION lifeos_record_change();
CREATE TRIGGER lifeos_calendar_history BEFORE INSERT OR UPDATE ON public.lifeos_calendar_events FOR EACH ROW EXECUTE FUNCTION lifeos_record_change();
