#!/usr/bin/env python3
"""Optimize MR card PNG assets and refresh their JSON URLs.

The short URL itself is generated by ai-MRbot/legacy_app.py from CASE_LIST.
This script handles the matching image work so both steps can happen in the
same GitHub push.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote, unquote, urlparse

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "ai-MRbot" / "templates"
LEGACY_APP = ROOT / "ai-MRbot" / "legacy_app.py"
REPO_PREFIX = "https://mrbusinesslab.github.io/MR_card/"
CARD_SIZE = (720, 1080)


def load_case_ids() -> set[str]:
    tree = ast.parse(LEGACY_APP.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "CASE_LIST"
            for target in node.targets
        ):
            values = ast.literal_eval(node.value)
            return {str(item["case"]) for item in values}
    raise RuntimeError("找不到 CASE_LIST")


def repo_path_from_url(url: str) -> str | None:
    parsed = urlparse(url)
    if parsed.netloc == "mrbusinesslab.github.io" and parsed.path.startswith("/MR_card/"):
        return unquote(parsed.path[len("/MR_card/"):])
    if parsed.netloc == "github.com" and "/mrbusinesslab/MR_card/blob/main/" in parsed.path:
        return unquote(parsed.path.split("/blob/main/", 1)[1])
    return None


def pages_url(path: Path) -> str:
    relative = path.relative_to(ROOT).as_posix()
    encoded = "/".join(quote(part, safe="") for part in relative.split("/"))
    blob_sha = subprocess.check_output(
        ["git", "hash-object", str(path)], cwd=ROOT, text=True
    ).strip()
    return f"{REPO_PREFIX}{encoded}?v={blob_sha[:12]}"


def optimize_png(source: Path, target: Path) -> None:
    with Image.open(source) as image:
        image = image.convert("RGBA")
        background = Image.new("RGB", image.size, "white")
        background.paste(image, mask=image.getchannel("A"))
        if background.size != CARD_SIZE:
            background = background.resize(CARD_SIZE, Image.Resampling.LANCZOS)
        target.parent.mkdir(parents=True, exist_ok=True)
        background.save(
            target,
            "JPEG",
            quality=88,
            subsampling=0,
            optimize=True,
            progressive=True,
        )


def find_image_node(value):
    if isinstance(value, dict):
        if value.get("type") == "image" and value.get("url"):
            return value
        for child in value.values():
            found = find_image_node(child)
            if found:
                return found
    elif isinstance(value, list):
        for child in value:
            found = find_image_node(child)
            if found:
                return found
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--changed-file",
        action="append",
        default=[],
        help="Repository-relative changed PNG path; repeat as needed.",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Process every PNG referenced by CASE_LIST card JSON files.",
    )
    args = parser.parse_args()

    case_ids = load_case_ids()
    changed = {
        Path(path).as_posix()
        for path in args.changed_file
        if path.lower().endswith(".png")
    }
    if not changed and not args.all:
        print("沒有需要處理的 PNG")
        return 0

    errors: list[str] = []
    optimized: dict[str, Path] = {}
    json_updates = 0

    for json_path in sorted(TEMPLATES.glob("case*/card_*.json")):
        case_id = json_path.parent.name
        if case_id not in case_ids:
            continue

        card = json.loads(json_path.read_text(encoding="utf-8"))
        pages = card.get("contents", [])
        changed_json = False

        for page_number, page in enumerate(pages, start=1):
            image_node = find_image_node(page)
            if not image_node:
                errors.append(f"{json_path}: 第 {page_number} 頁找不到圖片")
                continue

            current_path = repo_path_from_url(str(image_node["url"]))
            if not current_path:
                continue

            current = ROOT / current_path
            png_source = current if current.suffix.lower() == ".png" else current.with_suffix(".png")
            png_relative = png_source.relative_to(ROOT).as_posix()
            # A metadata-only run prepares cards that still point at PNG.
            # A directly changed PNG also refreshes an already optimized JPG.
            should_process = (
                args.all and current.suffix.lower() == ".png"
            ) or png_relative in changed

            if not should_process:
                continue
            if not png_source.exists():
                errors.append(f"{json_path}: 找不到 {png_relative}")
                continue

            jpg_target = png_source.with_suffix(".jpg")
            optimize_png(png_source, jpg_target)
            optimized[png_relative] = jpg_target
            image_node["url"] = pages_url(jpg_target)
            changed_json = True

        if changed_json:
            json_path.write_text(
                json.dumps(card, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            json_updates += 1

    # A changed case PNG must belong to a CASE_LIST entry and a card JSON.
    handled = set(optimized)
    for path in sorted(changed - handled):
        parts = Path(path).parts
        if len(parts) >= 4 and parts[:2] == ("ai-MRbot", "templates"):
            case_id = parts[2]
            if case_id not in case_ids:
                errors.append(f"{path}: {case_id} 尚未加入 CASE_LIST")
            else:
                errors.append(f"{path}: 找不到引用這張圖的 card JSON")

    if errors:
        print("\n".join(f"錯誤：{message}" for message in errors), file=sys.stderr)
        return 1

    print(f"完成 {len(optimized)} 張 JPG、更新 {json_updates} 份 JSON")
    for source, target in sorted(optimized.items()):
        print(f"- {source} -> {target.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
